// Auto-generated file - do not edit manually
// Generated by scripts/generate-constants.js

export const VERSION = "5.0.0-rc01";
export const PACKAGE_NAME = "@keenmate/svelte-treeview-canvas";
export const AUTHOR = "KeenMate";
export const LICENSE = "MIT";
export const REPOSITORY = "git+https://github.com/keenmate/svelte-treeview-canvas.git";
export const HOMEPAGE = "https://github.com/keenmate/svelte-treeview-canvas#readme";
